import {
  pgTable,
  serial,
  text,
  integer,
  numeric,
  date,
  timestamp,
  index,
  foreignKey,
} from "drizzle-orm/pg-core";

export const users = pgTable(
  "users",
  {
    id: serial().primaryKey(),
    phone: text().notNull().unique(),
    name: text(),
    surname: text(),
    nationalId: text("national_id").unique(),
    birthDate: date("birth_date"),
    email: text(),
    userType: text("user_type").default("student").notNull(),
    isActive: integer("is_active").default(1).notNull(),
    appLanguage: text("app_language").default("en"),
    fcmToken: text("fcm_token"),
    imageUrl: text("image_url"),
    profileComplete: integer("profile_complete").default(0).notNull(),
    educationLevel: text("education_level"),
    parentId: integer("parent_id"),
    isVerified: integer("is_verified").default(0).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
    credit: numeric("credit", { precision: 12, scale: 2 }),
    bankAccountNumber: text("bank_account_number"),
    bankShebaNumber: text("bank_sheba_number"),
    bankCardNumber: text("bank_card_number"),
    coinBalance: integer("coin_balance").default(0).notNull(),
  },
  (table) => [
    index("idx_users_is_active").on(table.isActive),
    index("idx_users_parent_id").on(table.parentId),
    index("idx_users_user_type").on(table.userType),
    index("idx_users_email").on(table.email),
    index("idx_users_phone").on(table.phone),
    foreignKey({
      columns: [table.parentId],
      foreignColumns: [table.id],
      name: "users_parent_id_users_id_fk",
    }),
  ],
);
